// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StartResult is returned by StartSync.
 */
export interface StartResult {
    "ok": boolean;

    /**
     * route to show instead, on failure
     */
    "step"?: string;
    "message"?: string;
}
