// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrickAccount is brick's /v1/account response.
 */
export interface BrickAccount {
    "accountId": string;
    "clientId": string;
}

/**
 * BrickActivityEvent is one entry from brick's /v1/activity feed.
 */
export interface BrickActivityEvent {
    "kind": string;
    "relPath": string;
    "at": string;
}

/**
 * BrickCounters are cumulative counts for the running brick process.
 */
export interface BrickCounters {
    "uploaded": number;
    "downloaded": number;
    "deleted": number;
    "moved": number;
}

/**
 * BrickDaemonResult mirrors daemonJSONOutput from brick-cli's
 * `-d --json` output (see brick-cli's cmd/brick/daemon_json.go) — the one
 * JSON line brick prints for a companion app starting it in daemon mode.
 * Status is "ok" or "error"; Code is only set on error ("already_running",
 * "setup_required", "start_failed", ...).
 */
export interface BrickDaemonResult {
    "status": string;
    "pid"?: number;
    "logPath"?: string;
    "folder"?: string;
    "code"?: string;
    "message"?: string;
}

/**
 * BrickInFlight is the file transfer currently in progress, if any.
 */
export interface BrickInFlight {
    "relPath": string;
    "direction": string;
}

/**
 * BrickLocateResult reports whether the brick CLI binary could be found.
 */
export interface BrickLocateResult {
    "found": boolean;
    "path": string;
}

/**
 * BrickRunResult is the outcome of running a brick subcommand to
 * completion (setup or install) — for callers that need the final exit
 * code rather than the live output stream.
 */
export interface BrickRunResult {
    "exitCode": number;
    "ok": boolean;
}

/**
 * BrickSelfTestCheck is one entry in the "checks" array of `brick
 * --self-test`'s JSON report.
 */
export interface BrickSelfTestCheck {
    "id": string;
    "status": string;
    "message": string;
}

/**
 * BrickSelfTestResult is the JSON brick prints for
 * `brick --self-test --no-upgrade-check`.
 */
export interface BrickSelfTestResult {
    "status": string;
    "version": string;
    "ready": boolean;
    "checks": BrickSelfTestCheck[] | null;
}

/**
 * BrickStatus is brick's /v1/status response, plus Running (set locally:
 * false whenever brick couldn't be reached at all, rather than an HTTP
 * error).
 */
export interface BrickStatus {
    "state": string;
    "folder": string;
    "lastError"?: string;
    "lastSyncCompletedAt"?: string;
    "counters": BrickCounters;
    "inFlight": BrickInFlight | null;
    "running": boolean;
}
