// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StartResult is returned by StartSync.
 */
export interface StartResult {
    "ok": boolean;

    /**
     * route to show instead, on failure
     */
    "step"?: string;
    "message"?: string;
}

/**
 * UpdateView is what the update window shows. Every path that opens the
 * window sets one first, so the window itself holds no state of its own.
 */
export interface UpdateView {
    "state": string;
    "current": string;

    /**
     * Latest is the newer version on offer, set only in the "available" state.
     */
    "latest"?: string;

    /**
     * Error explains a "failed" check, in the check's own words.
     */
    "error"?: string;
}
