// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OnboardingService drives the setup window: startup routing and the
 * onboarding wizard. All logic lives in internal/onboarding (tested without
 * Wails); this is the thin adapter that adds native dialogs, the browser and
 * window control. Bound via application.NewService in main.go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auth$0 from "./internal/auth/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as onboarding$0 from "./internal/onboarding/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Accounts returns the accounts to pick from.
 */
export function Accounts(): $CancellablePromise<auth$0.Account[] | null> {
    return $Call.ByID(3053688808);
}

/**
 * AwaitLogin resolves once the browser login completes (or fails/times out).
 */
export function AwaitLogin(): $CancellablePromise<onboarding$0.LoginResult | null> {
    return $Call.ByID(3210123299);
}

/**
 * BeginLogin starts the login callback server, opens the browser and returns
 * the authorization URL (shown in the UI as a fallback link).
 */
export function BeginLogin(): $CancellablePromise<string> {
    return $Call.ByID(3252784606);
}

/**
 * CancelLogin aborts a pending AwaitLogin.
 */
export function CancelLogin(): $CancellablePromise<void> {
    return $Call.ByID(3908308291);
}

/**
 * Checklist returns the completed onboarding steps.
 */
export function Checklist(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3302758324);
}

/**
 * ChooseSyncFolder records the chosen folder and reports whether it has files.
 */
export function ChooseSyncFolder(path: string): $CancellablePromise<onboarding$0.FolderChoice | null> {
    return $Call.ByID(814884866, path);
}

/**
 * ConfirmSyncFolder saves the chosen folder with its first-sync conflict mode.
 */
export function ConfirmSyncFolder(conflictMode: string): $CancellablePromise<string> {
    return $Call.ByID(207543275, conflictMode);
}

/**
 * Connect checks the Storage API and returns what the scope step needs.
 */
export function Connect(): $CancellablePromise<onboarding$0.ScopeInfo | null> {
    return $Call.ByID(3572942714);
}

/**
 * CreateFolderInHome creates a folder (or nested path) under home.
 */
export function CreateFolderInHome(rel: string): $CancellablePromise<string> {
    return $Call.ByID(2146348232, rel);
}

/**
 * DefaultSyncFolder is ~/Brick.
 */
export function DefaultSyncFolder(): $CancellablePromise<string> {
    return $Call.ByID(3853118822);
}

/**
 * FinishOnboarding records the end of the wizard (adds "Done and ready to
 * go!") without starting sync yet.
 */
export function FinishOnboarding(): $CancellablePromise<string[] | null> {
    return $Call.ByID(4071276106);
}

/**
 * HideWindow hides the setup window.
 */
export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(1924847320);
}

/**
 * HomeDir is the user's home directory.
 */
export function HomeDir(): $CancellablePromise<string> {
    return $Call.ByID(2258703330);
}

/**
 * OpenURL opens a URL in the default browser.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(534779869, url);
}

/**
 * PickDirectory shows a native directory picker starting in startDir. Returns
 * "" when cancelled.
 */
export function PickDirectory(startDir: string, title: string): $CancellablePromise<string> {
    return $Call.ByID(1038641632, startDir, title);
}

/**
 * Route decides which screen the setup window should show. When syncing is
 * already running it returns "ready".
 */
export function Route(): $CancellablePromise<onboarding$0.Route> {
    return $Call.ByID(1807476905);
}

/**
 * SelectAccount makes an account active.
 */
export function SelectAccount(id: string): $CancellablePromise<void> {
    return $Call.ByID(2920055571, id);
}

/**
 * SetRemoteAccess saves the remote-file-access decision.
 */
export function SetRemoteAccess(enabled: boolean, root: string): $CancellablePromise<void> {
    return $Call.ByID(2711039084, enabled, root);
}

/**
 * SetSyncScope saves which folders to sync.
 */
export function SetSyncScope(all: boolean, exclude: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3468232781, all, exclude);
}

/**
 * ShowWindow shows and focuses the setup window.
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(2390568069);
}

/**
 * StartSync starts syncing with any decisions from a just-finished wizard.
 * On failure it says which route to show instead.
 */
export function StartSync(): $CancellablePromise<$models.StartResult> {
    return $Call.ByID(2804897859);
}
