// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StartupService drives the startup status window: checking whether brick
 * is already running, self-testing and (re-)running setup when it isn't,
 * and installing the CLI when it's missing entirely. Bound to the frontend
 * via application.NewService in main.go; every exported method here is
 * callable from TypeScript through the generated bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * InstallBrick runs the platform-specific install command, streaming its
 * output line by line as "brick:install-output" events, and resolves once
 * it exits.
 */
export function InstallBrick(): $CancellablePromise<$models.BrickRunResult> {
    return $Call.ByID(3271732736);
}

/**
 * LocateBrick reports whether the brick CLI binary can be found, and where.
 */
export function LocateBrick(): $CancellablePromise<$models.BrickLocateResult> {
    return $Call.ByID(4018294455);
}

/**
 * QuitApp exits the whole app — used by the startup window's "Close Brick"
 * action, when the user declines to install the CLI.
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(835856990);
}

/**
 * RunSetup runs `brick --setup-and-exit` inside a new native terminal
 * window — brick's guided setup is interactive (it can prompt for login,
 * confirmations, etc.), so it needs a real TTY rather than the captured
 * output runStreamed uses for non-interactive commands. Resolves once the
 * terminal-run command exits (see terminal.go).
 */
export function RunSetup(): $CancellablePromise<$models.BrickRunResult> {
    return $Call.ByID(1288841066);
}

/**
 * SelfTest runs `brick --self-test --no-upgrade-check` and returns its
 * parsed report.
 */
export function SelfTest(): $CancellablePromise<$models.BrickSelfTestResult> {
    return $Call.ByID(3705108278);
}

/**
 * StartBrick launches brick's sync daemon in the background so it keeps
 * running independently of this app.
 */
export function StartBrick(): $CancellablePromise<void> {
    return $Call.ByID(2888731709);
}
