// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService exposes the in-process sync engine to the status popover. It
 * replaces the old control-API client with the same method names and JSON
 * shapes. Bound via application.NewService in main.go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runner$0 from "./internal/runner/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as syncengine$0 from "./internal/syncengine/models.js";

/**
 * Activity returns up to limit recent sync events, newest first.
 */
export function Activity(limit: number): $CancellablePromise<syncengine$0.ActivityEvent[] | null> {
    return $Call.ByID(2574522431, limit);
}

/**
 * OpenFolder opens the sync folder in the file manager.
 */
export function OpenFolder(): $CancellablePromise<void> {
    return $Call.ByID(2662748178);
}

/**
 * OpenSetup opens the setup window (not-configured / auth-required /
 * locked / stopped states offer this from the popover).
 */
export function OpenSetup(): $CancellablePromise<void> {
    return $Call.ByID(2409016551);
}

/**
 * Pause pauses syncing (the watcher keeps running, so resuming is instant).
 */
export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(3371829380);
}

/**
 * Resume resumes syncing.
 */
export function Resume(): $CancellablePromise<void> {
    return $Call.ByID(1996385421);
}

/**
 * Status returns the current sync status (see runner.Status).
 */
export function Status(): $CancellablePromise<runner$0.Status> {
    return $Call.ByID(3788943212);
}
