// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService owns everything about updates the UI can see: the window's
 * state, its buttons, and the checks that feed both. Bound via
 * application.NewService in main.go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Continue dismisses the update window without installing.
 */
export function Continue(): $CancellablePromise<void> {
    return $Call.ByID(4091967633);
}

/**
 * InstallUpdate launches the installer in the user's default terminal and
 * quits the app, which closes every window. The terminal survives the quit
 * since it's a separate process.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2153346210);
}

/**
 * View returns what the window should show. The window fetches it on load, in
 * case it wasn't listening yet for the "update:view" event that set it.
 */
export function View(): $CancellablePromise<$models.UpdateView | null> {
    return $Call.ByID(98759281);
}
