// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService drives the update window: what it shows (Info, set once the
 * startup check in main.go finds a newer release) and its two buttons.
 * Bound via application.NewService in main.go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "./internal/update/models.js";

/**
 * Continue dismisses the update window without installing.
 */
export function Continue(): $CancellablePromise<void> {
    return $Call.ByID(4091967633);
}

/**
 * Info returns the update found at startup, or nil if none (up to date, or
 * the check failed/timed out). The window loads hidden and calls this itself
 * in case it missed the "update:available" event emitted when the check
 * finishes.
 */
export function Info(): $CancellablePromise<update$0.Info | null> {
    return $Call.ByID(940036348);
}

/**
 * InstallUpdate launches the installer in the user's default terminal and
 * quits the app, which closes every window. The terminal survives the quit
 * since it's a separate process.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2153346210);
}
