// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Account is one entry from /v1/accounts.
 */
export interface Account {
    "id": string;
    "name": string;
}
