// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrickService is bound to the frontend via application.NewService in
 * main.go; every exported method here is callable from TypeScript through
 * the generated bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Account returns the logged-in account/client IDs, or a zero value (not an
 * error) when brick isn't running.
 */
export function Account(): $CancellablePromise<$models.BrickAccount> {
    return $Call.ByID(454940487);
}

/**
 * Activity returns the most recent sync events, newest first. Returns an
 * empty list (not an error) when brick isn't running.
 */
export function Activity(limit: number): $CancellablePromise<$models.BrickActivityEvent[] | null> {
    return $Call.ByID(2028017317, limit);
}

/**
 * Pause stops brick's reconcile loop until Resume is called.
 */
export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(2497774170);
}

/**
 * QuitBrick gracefully shuts down the brick sync process itself — distinct
 * from quitting this tray app, which just hides the UI and leaves brick's
 * sync running.
 */
export function QuitBrick(): $CancellablePromise<void> {
    return $Call.ByID(3118508848);
}

/**
 * Resume clears a pause and immediately wakes brick's reconcile loop.
 */
export function Resume(): $CancellablePromise<void> {
    return $Call.ByID(1225770875);
}

/**
 * Status returns brick's current sync status. When brick isn't running, it
 * returns {State: "not-running", Running: false} rather than an error,
 * since that's an expected state the tray UI needs to render normally.
 */
export function Status(): $CancellablePromise<$models.BrickStatus> {
    return $Call.ByID(586161754);
}
