// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrickAccount is brick's /v1/account response.
 */
export interface BrickAccount {
    "accountId": string;
    "clientId": string;
}

/**
 * BrickActivityEvent is one entry from brick's /v1/activity feed.
 */
export interface BrickActivityEvent {
    "kind": string;
    "relPath": string;
    "at": string;
}

/**
 * BrickCounters are cumulative counts for the running brick process.
 */
export interface BrickCounters {
    "uploaded": number;
    "downloaded": number;
    "deleted": number;
}

/**
 * BrickInFlight is the file transfer currently in progress, if any.
 */
export interface BrickInFlight {
    "relPath": string;
    "direction": string;
}

/**
 * BrickStatus is brick's /v1/status response, plus Running (set locally:
 * false whenever brick couldn't be reached at all, rather than an HTTP
 * error).
 */
export interface BrickStatus {
    "state": string;
    "folder": string;
    "lastError"?: string;
    "lastSyncCompletedAt"?: string;
    "counters": BrickCounters;
    "inFlight": BrickInFlight | null;
    "running": boolean;
}
