// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info describes an available update.
 */
export interface Info {
    "current": string;
    "latest": string;
}
