// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Quota is GET /v1/accounts/{id}/quota.
 */
export interface Quota {
    "quotaBytes": number;
    "usedBytes": number;
    "remainingBytes": number;
    "callingUser": QuotaUser;
}

/**
 * QuotaUser is the calling user's share of the account usage.
 */
export interface QuotaUser {
    "usedBytes": number;
    "usedVideoBytes": number;
    "usedImageBytes": number;
    "usedOtherBytes": number;
}
