// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auth$0 from "../auth/models.js";

/**
 * FolderChoice is returned by ChooseSyncFolder.
 */
export interface FolderChoice {
    "folder": string;
    "display": string;
    "hasFiles": boolean;
}

/**
 * LoginResult is returned by AwaitLogin.
 */
export interface LoginResult {
    "greeting": string;
    "accounts": auth$0.Account[] | null;

    /**
     * AccountSelected is true when there was exactly one account and it was
     * selected automatically (brick-cli's selectAccount).
     */
    "accountSelected": boolean;
}

/**
 * Route tells the UI where to go.
 */
export interface Route {
    "step": string;

    /**
     * FirstRun is true when config.yaml was just created (show the welcome
     * greeting rather than a plain "log in").
     */
    "firstRun": boolean;
    "message": string;
    "detail"?: string;
}

/**
 * ScopeInfo is returned by Connect: whether to show the sync-scope step.
 */
export interface ScopeInfo {
    "showScope": boolean;
    "showRemote": boolean;
    "totalHuman": string;
    "folders": string[] | null;
    "alreadyExcluded": string[] | null;
}
