// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as syncengine$0 from "../syncengine/models.js";

/**
 * Status is what the UI renders (engine status plus app-level state). JSON
 * shape is a superset of brick-cli's /v1/status.
 */
export interface Status {
    /**
     * starting | syncing | idle | error | paused
     */
    "state": string;
    "folder": string;
    "lastError"?: string;
    "lastSyncCompletedAt"?: string;
    "counters": syncengine$0.Counters;
    "inFlight": syncengine$0.InFlight | null;
    "running": boolean;
}
