// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActivityEvent is one recent-activity entry. Kinds: upload, update,
 * download, trash, trash-folder, remove, remove-folder, move, move-folder,
 * keep-both, verify (content confirmed identical, so nothing was
 * transferred — see Engine.verifyUnsyncedFileMatches).
 */
export interface ActivityEvent {
    "kind": string;
    "relPath": string;
    "at": string;
}

/**
 * Counters are cumulative since the engine was created.
 */
export interface Counters {
    "uploaded": number;
    "downloaded": number;
    "deleted": number;
    "moved": number;
}

/**
 * InFlight is the single transfer in progress.
 */
export interface InFlight {
    "relPath": string;

    /**
     * upload | download
     */
    "direction": string;
}
